#!/bin/bash
BACKUP_LABEL=${BACKUP_LABEL:-"tech.embrio.backup"}
BACKUP_DIR=${BACKUP_DIR:-"$(pwd)/volumes"}
GS_BUCKET_NAME=${GS_BUCKET_NAME:-""}
GS_SA_KEY=${GS_SA_KEY:-""}
AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-""}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-""}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-""}